#include "ft_printf.h"

int		main(void)
{
	unsigned int x = 4294967161;
	printf("|%-4.x|\n",x);
	ft_printf("|%-4.x|\n",x);

	printf("------------------\n");
	printf("|%-4.*x|\n",-4,x);
	ft_printf("|%-4.*x|\n",-4,x);
	printf("------------------\n");
	printf("|%-4.x|\n", x);
	ft_printf("|%-4.x|\n", x);
	printf("-------------\n");
	printf("|%-4.*x|\n",-4, x);
	ft_printf("|%-4.*x|\n",-4, x);

	 printf("--------------------\n");
	ft_printf("%4x\n", x);
	printf("%4x\n", x);
	printf("--------------------\n");
	printf("|%04x|\n",x);
	ft_printf("|%04x|\n",x);
	printf("--------------------\n");
	printf("|%04x|\n",123);
	ft_printf("|%04x|\n",123);
	printf("--------------------\n");
	printf("|%010x|\n",x);
	ft_printf("|%010x|\n",x);
	printf("--------------------\n");
	printf("|%04.x|\n",x);
	ft_printf("|%04.x|\n",x);
	printf("--------------------\n");
	printf("|%010x|\n",x);
	ft_printf("|%010x|\n",x);
	printf("--------------------\n");
	printf("|%-04x|\n",x);
	ft_printf("|%-04x|\n",x);
	printf("--------------------\n");
		printf("|%-010.3x|\n",x);
	ft_printf("|%-010.3x|\n",x);
	printf("--------------------\n");
	printf("|%-010.3x|\n",x);
	ft_printf("|%-010.3x|\n",x);
	printf("--------------------\n");
	printf("|%*.*x|\n",3,2,x);
	ft_printf("|%*.*x|\n",3,2,x);
	printf("--------------------\n");
	printf("|%x,,%x,,|\n",13,x);
	ft_printf("|%x,,%x,,|\n",13,x);

	// printf("unsignedint:%u\n",u);
	// ft_printf("ft_unsignedint:%u\n",u);
	// printf("------------------\n");
	// printf("-unsignedint:%u\n",uu);
	// ft_printf("ft_-unsignedint:%u\n",uu);
	// printf("------------------\n");
	// printf("|%-4.*u|\n",-4,u);
	// ft_printf("|%-4.*u|\n",-4,u);
	// printf("------------------\n");
	// printf("|%-4.u|\n", u);
	// ft_printf("|%-4.u|\n", u);
	// printf("-------------\n");
	// printf("|%-4.*u|\n",-4, u);
	// ft_printf("|%-4.*u|\n",-4, u);

	//  printf("--------------------\n");
	// ft_printf("%4u\n", u);
	// printf("%4u\n", u);
	// printf("--------------------\n");
	// printf("|%04u|\n",u);
	// ft_printf("|%04u|\n",u);
	// printf("--------------------\n");
	// printf("|%04u|\n",123);
	// ft_printf("|%04u|\n",123);
	// printf("--------------------\n");
	// printf("|%010u|\n",u);
	// ft_printf("|%010u|\n",u);
	// printf("--------------------\n");
	// printf("|%04.u|\n",u);
	// ft_printf("|%04.u|\n",u);
	// printf("--------------------\n");
	// printf("|%010u|\n",u);
	// ft_printf("|%010u|\n",u);
	// printf("--------------------\n");
	// printf("|%-04u|\n",u);
	// ft_printf("|%-04u|\n",u);
	// printf("--------------------\n");
	// 	printf("|%-010.3u|\n",u);
	// ft_printf("|%-010.3u|\n",u);
	// printf("--------------------\n");
	// printf("|%-010.3u|\n",u);
	// ft_printf("|%-010.3u|\n",u);
	// printf("--------------------\n");
	// printf("|%*.*u|\n",3,2,u);
	// ft_printf("|%*.*u|\n",3,2,u);
	// printf("--------------------\n");
	// printf("|%u,,%u,,|\n",13,u);
	// ft_printf("|%u,,%u,,|\n",13,u);

	// printf("|%-4.i|\n", i);
	// ft_printf("|%-4.i|\n", i);
	// printf("-------------\n");
	// printf("|%-4.*i|\n",-4, i);
	// ft_printf("|%-4.*i|\n",-4, i);

	//  printf("--------------------\n");
	// ft_printf("%4i\n", i);
	// printf("%4i\n", i);
	// printf("--------------------\n");
	// printf("|%04i|\n",i);
	// ft_printf("|%04i|\n",i);
	// printf("--------------------\n");
	// printf("|%04i|\n",123);
	// ft_printf("|%04i|\n",123);
	// printf("--------------------\n");
	// printf("|%010i|\n",i);
	// ft_printf("|%010i|\n",i);
	// printf("--------------------\n");
	// printf("|%04.i|\n",i);
	// ft_printf("|%04.i|\n",i);
	// printf("--------------------\n");
	// printf("|%010i|\n",i);
	// ft_printf("|%010i|\n",i);
	// printf("--------------------\n");
	// printf("|%-04i|\n",i);
	// ft_printf("|%-04i|\n",i);
	// printf("--------------------\n");
	// 	printf("|%-010.3i|\n",i);
	// ft_printf("|%-010.3i|\n",i);
	// printf("--------------------\n");
	// printf("|%-010.3i|\n",i);
	// ft_printf("|%-010.3i|\n",i);
	// printf("--------------------\n");
	// printf("|%*.*i|\n",3,2,i);
	// ft_printf("|%*.*i|\n",3,2,i);
	// printf("--------------------\n");
	// printf("|%i,,%i,,|\n",13,i);
	// ft_printf("|%i,,%i,,|\n",13,i);

	// int d =12;
	// int a=ft_printf("-->|%0d|<--\n", -135);
	// int b= printf("-->|%0d|<--\n", -135);
	// printf("%d %d\n",a,b);
	// printf("--------------------\n");
	// ft_printf("%4d\n", 12);
	// printf("%4d\n", 12);
	// printf("--------------------\n");
	// printf("|%04d|\n",3);
	// ft_printf("|%04d|\n",3);
	// printf("--------------------\n");
	// printf("|%04.-6d|\n",3);
	// ft_printf("|%04.-6d|\n",3);
	// printf("--------------------\n");
	// printf("|%04d|\n",123);
	// ft_printf("|%04d|\n",123);
	// printf("--------------------\n");
	// printf("|%010d|\n",3);
	// ft_printf("|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%04.d|\n",3);
	// ft_printf("|%04.d|\n",3);
	// printf("--------------------\n");
	// printf("|%010d|\n",3);
	// ft_printf("|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%-04d|\n",3);
	// ft_printf("|%-04d|\n",3);
	// printf("--------------------\n");
	// printf("|%-010d|\n",3);
	// ft_printf("|%-010d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.2d|\n",3);
	// ft_printf("|%010.2d|\n",3);
	// printf("--------------------\n");
	// printf("|%0.0d|\n",3);
	// ft_printf("|%0.0d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.4d|\n",3);
	// ft_printf("|%010.4d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.4d|\n",-3);
	// ft_printf("|%010.4d|\n",-3);
	// printf("--------------------\n");
	// printf("-5:|%0.4d|\n",-3);
	// ft_printf( "-5:|%0.4d|\n",-3);
	// printf("--------------------\n");
	// printf("-4:|%0-10d|\n",3);
	// ft_printf("-4:|%0-10d|\n",3);
	// printf("--------------------\n");
	// printf("-3:|%0-4d|\n",12345);
	// ft_printf("-3:|%0-4d|\n",12345);
	// printf("--------------------\n");
	// printf("-2:|%010d|\n",3);
	// ft_printf("-2:|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%0-10.2d|\n",3);
	// ft_printf("|%0-10.2d|\n",3);
	// printf("--------------------\n");
	// printf("|%0-10.3d|\n",3);
	// ft_printf("|%0-10.3d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.3d|\n",12345);
	// ft_printf("|%010.3d|\n",12345);
	// printf("--------------------\n");
	// printf("|%-010.3d|\n",12345);
	// ft_printf("|%-010.3d|\n",12345);
	// printf("--------------------\n");
	// printf("|%-010.3d|\n",12);
	// ft_printf("|%-010.3d|\n",12);
	// printf("--------------------\n");
	// printf("|%*.*d|\n",3,2,-12);
	// ft_printf("|%*.*d|\n",3,2,-12);
	// printf("--------------------\n");
	// printf("|%d,,%d,,|\n",13,12);
	// ft_printf("|%d,,%d,,|\n",13,12);
	// printf("--------------------\n");
	// printf("|%10.-5d|\n",6);
	// ft_printf("|%10.-5d|\n",6);
	// printf("--------------------\n");
	// printf("|%10.-5d|\n",-6);
	// ft_printf("|%10.-5d|\n",-6);
	// printf("--------------------\n");
	// printf("|%10.5d|\n",-6);
	// ft_printf("|%10.5d|\n",-6);

	x = 12;
	//printf("\n10 nputnbr_base\n");
	ft_putnbr_base(x,"0123456789ABCDEF");
	//printf("%x",x);


}
