#include "ft_printf.h"

int		main(void)
{

// printf("-----------------\n");
// 	printf("printf:|%%09|\n");
// 	ft_printf("ft    :|%%09|\n");
// printf("-----------------\n");
// 	printf("%09s\n","hi low");
// 	ft_printf("%09s\n","hi low");
// 	printf("-----------------\n");
// 	printf("-%09s\n","hi low");
// 	ft_printf("-%09s\n","hi low");
// 	printf("-----------------\n");
// 	printf("%03s\n","hi low");
// 	ft_printf("%03s\n","hi low");

//  ft_printf("|%5.i|\n", 0);
//  printf("|%5.i|\n", 0);
//  	printf("-----------------\n");
//  ft_printf("|%-5.i|\n", 0);
//   printf("|%-5.i|\n", 0);

  	printf("-----------------\n");
 ft_printf("|%5.0d|\n", 0);
 printf("|%5.0d|\n", 0);
  	printf("-----------------\n");
 ft_printf("|%-5.u|\n", 0);
  printf("|%-5.u|\n", 0);
  	printf("-----------------\n");
 ft_printf("|%5.x|\n", 0);
 printf("|%5.x|\n", 0);
  	printf("-----------------\n");
 ft_printf("|%-5.0X|\n", 0);
  printf("|%-5.0X|\n", 0);
  printf("-----------------\n");
 ft_printf("|%-5.X|\n", 0);
  printf("|%-5.X|\n", 0);
  	printf("-----------------\n");
//  ft_printf("|%-102p%-91p%00*.32%|\n" ,(void*)17383623580121946936lu,(void*)6825043625903153404lu,-125);
//   printf("|%-102p%-91p%00*.32%|\n" ,(void*)17383623580121946936lu,(void*)6825043625903153404lu,-125);
//   	printf("-----------------\n");
// ft_printf("|%29p%0151.162x%---53.46u%-139.26X|\n" ,(void*)17894711340605174765lu,1565093748u,662758369u,3536629372u);
// printf("|%29p%0151.162x%---53.46u%-139.26X|\n" ,(void*)17894711340605174765lu,1565093748u,662758369u,3536629372u);
	//%% Tests
	// printf("%%\n");
	// ft_printf("%%\n");
	// printf("-----------------\n");
	// printf("%5%\n");
	// ft_printf("%5%\n");
	// printf("-----------------\n");
	// printf("%-5%\n");
	// ft_printf("%-5%\n");
	// printf("-----------------\n");
	// printf("%05%\n");
	// ft_printf("%05%\n");
	// printf("-----------------\n");
	// printf("%-05%\n");
	// ft_printf("%-05%\n");
	// printf("-----------------\n");
	// printf("%-05%\n");
	// ft_printf("%-05%\n");
	// printf("-----------------\n");
	// printf("%0-05%\n");
	// ft_printf("%0-05%\n");

	// char *abc = NULL;
	// printf("|%s|\n",abc);
	// ft_printf("|%s|\n",abc);
	// printf("-----------------\n");
	// printf("|%-16.s|\n",abc);
	// ft_printf("|%-16.s|\n",abc);
	// printf("-----------------\n");
	// printf("|%-16.*s|\n",-4,abc);
	// ft_printf("|%-16.*s|\n",-4,abc);
	// printf("-----------------\n");
	// printf("|%-10.*s|\n",-4,"abcdefghijklmnop");
	// ft_printf("|%-10.*s|\n",-4,"abcdefghijklmnop");
	// printf("-----------------\n");
	// printf("|%-10.*s|\n",9,"abcdefg");
	// ft_printf("|%-10.*s|\n",9,"abcdefg");
	// printf("-----------------\n");
	// printf("|%10.*s|\n",9,"abcdefg");
	// ft_printf("|%10.*s|\n",9,"abcdefg");
	// printf("-----------------\n");
	// printf("|%-10.6s|\n","abc");
	// ft_printf("|%-10.6s|\n","abc");
	// printf("-----------------\n");
	// printf("|%10.6s|\n","abc");
	// ft_printf("|%10.6s|\n","abc");
	// printf("-----------------\n");
	// printf("|%-10.6s|\n","abcdefg");
	// ft_printf("|%-10.6s|\n","abcdefg");
	// static char     a01;
	// static unsigned char a02;
	// static short a03;
	// static unsigned short a04;


	// ft_printf("|%p|\n", NULL);
	// printf("|%p|\n", NULL);
	//  printf("------------------\n");
	// ft_printf("%9.2p\n", 1234);
	// printf("%9.2p\n", 1234);
	//  printf("------------------\n");
	// ft_printf("%2.9p\n", 1234);
	// printf("%2.9p\n", 1234);
	// printf("------------------\n");
	// ft_printf("|%.5p|\n", 0);
	// printf("|%.5p|\n", 0);
	// printf("------------------\n");
	// ft_printf("|%.0p|\n", 0);
	// printf("|%.0p|\n", 0);
	// printf("------------------\n");
	// ft_printf("|%5p|\n", 0);
	// printf("|%5p|\n", 0);
	// printf("------------------\n");
	// ft_printf("|%10p|\n",&a01);
	// printf("|%10p|\n",&a01);
	// printf("------------------\n");
	// ft_printf("|%10p|\n",&a02);
	// printf("|%10p|\n",&a02);
	// printf("------------------\n");
	// ft_printf("|%12p|\n",&a03);
	// printf("|%12p|\n",&a03);
	// printf("------------------\n");
	// unsigned int x = 0;
	// printf("|%-4.x|\n",x);
	// ft_printf("|%-4.x|\n",x);

	// printf("------------------\n");
	// printf("|%-4.*x|\n",-4,x);
	// ft_printf("|%-4.*x|\n",-4,x);
	// printf("------------------\n");
	// printf("|%-4.x|\n", x);
	// ft_printf("|%-4.x|\n", x);
	// printf("-------------\n");
	// printf("|%-4.*x|\n",-4, x);
	// ft_printf("|%-4.*x|\n",-4, x);

	//  printf("--------------------\n");
	// ft_printf("%4x\n", x);
	// printf("%4x\n", x);
	// printf("--------------------\n");
	// printf("|%04x|\n",x);
	// ft_printf("|%04x|\n",x);
	// printf("--------------------\n");
	// printf("|%04x|\n",123);
	// ft_printf("|%04x|\n",123);
	// printf("--------------------\n");
	// printf("|%010x|\n",x);
	// ft_printf("|%010x|\n",x);
	// printf("--------------------\n");
	// printf("|%04.x|\n",x);
	// ft_printf("|%04.x|\n",x);
	// printf("--------------------\n");
	// printf("|%010x|\n",x);
	// ft_printf("|%010x|\n",x);
	// printf("--------------------\n");
	// printf("|%-04x|\n",x);
	// ft_printf("|%-04x|\n",x);
	// printf("--------------------\n");
	// 	printf("12:|%-010.3x|\n",x);
	// ft_printf("12:|%-010.3x|\n",x);
	// printf("--------------------\n");
	// printf("|%-010.3x|\n",x);
	// ft_printf("|%-010.3x|\n",x);
	// printf("--------------------\n");
	// printf("|%*.*x|\n",3,2,x);
	// ft_printf("|%*.*x|\n",3,2,x);
	// printf("--------------------\n");
	// printf("|%x,,%x,,|\n",13,x);
	// ft_printf("|%x,,%x,,|\n",13,x);
	// printf("--------------------\n");
	// printf("|%-4x|\n",x);
	// ft_printf("|%-4x|\n",x);

	// unsigned int p = 0;
	// printf("|%-4.X|\n",x);
	// ft_printf("|%-4.X|\n",x);

	// printf("------------------\n");
	// printf("|%-4.*X|\n",-4,x);
	// ft_printf("|%-4.*X|\n",-4,x);
	// printf("------------------\n");
	// printf("|%-4.X|\n", x);
	// ft_printf("|%-4.X|\n", x);
	// printf("-------------\n");
	// printf("|%-4.*X|\n",-4, x);
	// ft_printf("|%-4.*X|\n",-4, x);

	//  printf("--------------------\n");
	// ft_printf("%4X\n", x);
	// printf("%4X\n", x);
	// printf("--------------------\n");
	// printf("|%04X|\n",x);
	// ft_printf("|%04X|\n",x);
	// printf("--------------------\n");
	// printf("|%04X|\n",123);
	// ft_printf("|%04X|\n",123);
	// printf("--------------------\n");
	// printf("|%04x|\n",123);
	// ft_printf("|%04x|\n",123);
	// printf("--------------------\n");
	// printf("|%010x|\n",x);
	// ft_printf("|%010x|\n",x);
	// printf("--------------------\n");
	// printf("|%04.x|\n",x);
	// ft_printf("|%04.x|\n",x);
	// printf("--------------------\n");
	// printf("|%010x|\n",x);
	// ft_printf("|%010x|\n",x);
	// printf("--------------------\n");
	// printf("|%-04x|\n",x);
	// ft_printf("|%-04x|\n",x);
	// printf("--------------------\n");
	// 	printf("12:|%-010.3x|\n",x);
	// ft_printf("12:|%-010.3x|\n",x);
	// printf("--------------------\n");
	// printf("|%-010.3x|\n",x);
	// ft_printf("|%-010.3x|\n",x);
	// printf("--------------------\n");
	// printf("|%*.*x|\n",3,2,x);
	// ft_printf("|%*.*x|\n",3,2,x);
	// printf("--------------------\n");
	// printf("|%x,,%x,,|\n",13,x);
	// ft_printf("|%x,,%x,,|\n",13,x);
	// printf("--------------------\n");
	// printf("|%-4x|\n",x);
	// ft_printf("|%-4x|\n",x);



	// printf("unsignedint:%u\n",u);
	// ft_printf("ft_unsignedint:%u\n",u);
	// printf("------------------\n");
	// printf("-unsignedint:%u\n",uu);
	// ft_printf("ft_-unsignedint:%u\n",uu);
	// printf("------------------\n");
	// printf("|%-4.*u|\n",-4,u);
	// ft_printf("|%-4.*u|\n",-4,u);
	// printf("------------------\n");
	// printf("|%-4.u|\n", u);
	// ft_printf("|%-4.u|\n", u);
	// printf("-------------\n");
	// printf("|%-4.*u|\n",-4, u);
	// ft_printf("|%-4.*u|\n",-4, u);


	//  printf("--------------------\n");
	// ft_printf("%4u\n", u);
	// printf("%4u\n", u);
	// printf("--------------------\n");
	// printf("|%04u|\n",u);
	// ft_printf("|%04u|\n",u);
	// printf("--------------------\n");
	// printf("|%04u|\n",123);
	// ft_printf("|%04u|\n",123);
	// printf("--------------------\n");
	// printf("|%010u|\n",u);
	// ft_printf("|%010u|\n",u);
	// printf("--------------------\n");
	// printf("|%04.u|\n",u);
	// ft_printf("|%04.u|\n",u);
	// printf("--------------------\n");
	// printf("|%010u|\n",u);
	// ft_printf("|%010u|\n",u);
	// printf("--------------------\n");
	// printf("|%-04u|\n",u);
	// ft_printf("|%-04u|\n",u);
	// printf("--------------------\n");
	// 	printf("|%-010.3u|\n",u);
	// ft_printf("|%-010.3u|\n",u);
	// printf("--------------------\n");
	// printf("|%-010.3u|\n",u);
	// ft_printf("|%-010.3u|\n",u);
	// printf("--------------------\n");
	// printf("|%*.*u|\n",3,2,u);
	// ft_printf("|%*.*u|\n",3,2,u);
	// printf("--------------------\n");
	// printf("|%u,,%u,,|\n",13,u);
	// ft_printf("|%u,,%u,,|\n",13,u);

	// printf("|%-4.i|\n", i);
	// ft_printf("|%-4.i|\n", i);
	// printf("-------------\n");
	// printf("|%-4.*i|\n",-4, i);
	// ft_printf("|%-4.*i|\n",-4, i);

	//  printf("--------------------\n");
	// ft_printf("%4i\n", i);
	// printf("%4i\n", i);
	// printf("--------------------\n");
	// printf("|%04i|\n",i);
	// ft_printf("|%04i|\n",i);
	// printf("--------------------\n");
	// printf("|%04i|\n",123);
	// ft_printf("|%04i|\n",123);
	// printf("--------------------\n");
	// printf("|%010i|\n",i);
	// ft_printf("|%010i|\n",i);
	// printf("--------------------\n");
	// printf("|%04.i|\n",i);
	// ft_printf("|%04.i|\n",i);
	// printf("--------------------\n");
	// printf("|%010i|\n",i);
	// ft_printf("|%010i|\n",i);
	// printf("--------------------\n");
	// printf("|%-04i|\n",i);
	// ft_printf("|%-04i|\n",i);
	// printf("--------------------\n");
	// 	printf("|%-010.3i|\n",i);
	// ft_printf("|%-010.3i|\n",i);
	// printf("--------------------\n");
	// printf("|%-010.3i|\n",i);
	// ft_printf("|%-010.3i|\n",i);
	// printf("--------------------\n");
	// printf("|%*.*i|\n",3,2,i);
	// ft_printf("|%*.*i|\n",3,2,i);
	// printf("--------------------\n");
	// printf("|%i,,%i,,|\n",13,i);
	// ft_printf("|%i,,%i,,|\n",13,i);

	// ft_printf("|%-4.d|\n", 0);
	// printf("|%-4.d|\n", 0);
	// int d =12;
	// int a=ft_printf("-->|%0d|<--\n", -135);
	// int b= printf("-->|%0d|<--\n", -135);
	// printf("%d %d\n",a,b);
	// printf("--------------------\n");
	// ft_printf("%4d\n", 12);
	// printf("%4d\n", 12);
	// printf("--------------------\n");
	// printf("|%04d|\n",3);
	// ft_printf("|%04d|\n",3);
	// printf("--------------------\n");
	// printf("|%04.-6d|\n",3);
	// ft_printf("|%04.-6d|\n",3);
	// printf("--------------------\n");
	// printf("|%04d|\n",123);
	// ft_printf("|%04d|\n",123);
	// printf("--------------------\n");
	// printf("|%010d|\n",3);
	// ft_printf("|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%04.d|\n",3);
	// ft_printf("|%04.d|\n",3);
	// printf("--------------------\n");
	// printf("|%010d|\n",3);
	// ft_printf("|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%-04d|\n",3);
	// ft_printf("|%-04d|\n",3);
	// printf("--------------------\n");
	// printf("|%-010d|\n",3);
	// ft_printf("|%-010d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.2d|\n",3);
	// ft_printf("|%010.2d|\n",3);
	// printf("--------------------\n");
	// printf("|%0.0d|\n",3);
	// ft_printf("|%0.0d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.4d|\n",3);
	// ft_printf("|%010.4d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.4d|\n",-3);
	// ft_printf("|%010.4d|\n",-3);
	// printf("--------------------\n");
	// printf("-5:|%0.4d|\n",-3);
	// ft_printf( "-5:|%0.4d|\n",-3);
	// printf("--------------------\n");
	// printf("-4:|%0-10d|\n",3);
	// ft_printf("-4:|%0-10d|\n",3);
	// printf("--------------------\n");
	// printf("-3:|%0-4d|\n",12345);
	// ft_printf("-3:|%0-4d|\n",12345);
	// printf("--------------------\n");
	// printf("-2:|%010d|\n",3);
	// ft_printf("-2:|%010d|\n",3);
	// printf("--------------------\n");
	// printf("|%0-10.2d|\n",3);
	// ft_printf("|%0-10.2d|\n",3);
	// printf("--------------------\n");
	// printf("|%0-10.3d|\n",3);
	// ft_printf("|%0-10.3d|\n",3);
	// printf("--------------------\n");
	// printf("|%010.3d|\n",12345);
	// ft_printf("|%010.3d|\n",12345);
	// printf("--------------------\n");
	// printf("|%-010.3d|\n",12345);
	// ft_printf("|%-010.3d|\n",12345);
	// printf("--------------------\n");
	// printf("ㅇㅣ놈|%-010.3d|\n",12);
	// ft_printf("ㅇㅣ놈|%-010.3d|\n",12);
	// printf("--------------------\n");
	// printf("|%*.*d|\n",3,2,-12);
	// ft_printf("|%*.*d|\n",3,2,-12);
	// printf("--------------------\n");
	// printf("|%d,,%d,,|\n",13,12);
	// ft_printf("|%d,,%d,,|\n",13,12);
	// printf("--------------------\n");
	// printf("|%10.-5d|\n",6);
	// ft_printf("|%10.-5d|\n",6);
	// printf("--------------------\n");
	// printf("|%10.-5d|\n",-6);
	// ft_printf("|%10.-5d|\n",-6);
	// printf("--------------------\n");
	// printf("|%10.5d|\n",-6);
	// ft_printf("|%10.5d|\n",-6);
	// printf("--------------------\n");
	// printf("|%-4d|\n",0);
	// ft_printf("|%-4d|\n",0);

	//x = 12;
	//printf("\n10 nputnbr_base\n");
	//printf("%x",x);
	// int u = 0;
	// printf("--------------------\n");
	// printf("|%-4.4u|\n",u);
	// ft_printf("|%-4.4u|\n",u);
	// printf("--------------------\n");
	// printf("|%-4u|\n",u);
	// ft_printf("|%-4u|\n",u);
	// printf("--------------------\n");
	// printf("|%00.0u|\n",-135);
	// ft_printf("|%00.0u|\n",-135);
	// printf("--------------------\n");
	// printf("|%00.0u|\n",-12);
	// ft_printf("|%00.0u|\n",-12);

}
